// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPITutorial.DBContext;

#nullable disable

namespace WebAPITutorial.Migrations
{
    [DbContext(typeof(KucoinVolContext))]
    [Migration("20230519182355_AddKucoinVolTable")]
    partial class AddKucoinVolTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPITutorial.Models.KucoinVolatilityEntity", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("KucoinVolatilityItems");
                });
#pragma warning restore 612, 618
        }
    }
}
