// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPITutorial.DBContexts;

#nullable disable

namespace WebAPITutorial.Migrations
{
    [DbContext(typeof(KucoinVolContext))]
    [Migration("20230519192245_AddVolALLTables_4")]
    partial class AddVolALLTables_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPITutorial.Models.ARB_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("ARB_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.BNB_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("BNB_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.BTC_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("BTC_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.DOGE_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("DOGE_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.ETH_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("ETH_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.LTC_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("LTC_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.MATIC_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("MATIC_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.SOL_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("SOL_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.UNI_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("UNI_USDT_Items", (string)null);
                });

            modelBuilder.Entity("WebAPITutorial.Models.XRP_USDT_Item", b =>
                {
                    b.Property<long>("KucoinVolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KucoinVolId"));

                    b.Property<decimal>("ChangePercentage")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuoteVolume")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.HasKey("KucoinVolId");

                    b.ToTable("XRP_USDT_Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
